### ISSUE TITLE
Cannot read properties of undefined (reading match)

### ISSUE THREAD

**Issue by lorypelli** [discordcf/typescript-bot-template#2]
![image](https://user-images.githubusercontent.com/87276663/209472964-ad55d40e-f3b6-4ca6-9fee-ddfe09abb45f.png)
I did the wrangler configuration but after using wrangler dev and started the server, this error happens (I also changed wrangler.toml files by adding my account id, guild id and public key)

**Comment by diogoalexsmachado** [comment]
Make sure the env variables are accessible to the wrangler (setting up the env name, for example)

`wrangler publish --env test`

Hope it helps
